import { Button } from '@mui/material';
import Head from 'next/head';
import * as React from 'react';
import styles from './../../styles/Home.module.css'
import LocalGroceryStoreIcon from '@mui/icons-material/LocalGroceryStore';
import BackspaceIcon from '@mui/icons-material/Backspace';
const Layout = ({handle , label}) => {

    return (
        <>
            <Head>
                <title>Fruit Shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.box} >
            <Button 
                variant="contained"
                onClick={handle} 
                startIcon={label==="Basket"? <LocalGroceryStoreIcon />:<BackspaceIcon />}>
                {label}
            </Button>
                {/* <Button variant="contained" onClick={handle}>{label}</Button> */}
                
            </div>
        </>
  )
}


export default Layout